#! /usr/bin/env python3

# This part is time-critical because of tab-completion
# Load only necessary modules to minimize the reaction time when user presses tab
# Especially do not load lssh_main when called for completion

import sys

if len(sys.argv) >= 2 and sys.argv[1] == '__complete__':
    import lssh_tabcomplete
    lssh_tabcomplete.main()
else:
    import lssh_main
    lssh_main.main()
