#! /usr/bin/env python3

import os, pwd, shutil, subprocess, sys

def remove_dir(name):
    print("Removing " + name + " ...")
    try:
        shutil.rmtree(name)
    except FileNotFoundError:
        print("  (did not exist)")
    except PermissionError as e:
        print("Got PermissionError: " + str(e))
        print("Note, that this system-wide uninstaller needs root permissions.")
        sys.exit(1)

def remove_file(note, name):
    print("Removing " + note + " in " + name + " ...")
    try:
        os.unlink(name)
    except FileNotFoundError:
        print("  (file did not exist)")

remove_dir("/usr/local/lib/lssh")
remove_dir("/var/local/lssh")

remove_file("sudo rule", "/etc/sudoers.d/lssh")
remove_file("lssh executable", "/usr/local/bin/lssh")
remove_file("bash completion file", "/etc/bash_completion.d/lssh_completion")
